### ISSUE TITLE
Loading the Metadata for GoalioRememberMeDoctrineORM\Entity\RememberMe

### ISSUE THREAD

**Issue by vadexito** [goalio/GoalioRememberMeDoctrineORM#3]
there seems to be a problem because the onbootstrap of the GoalioRememberMeModuleORM (where an authenticate event is triggered) is called after the one of the GoalioRememberMe module (where the entity xml configuration for the entity GoalioRememberMeDoctrineORM\Entity\RememberMe is loaded : i have got this error : 

Fatal error: Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'The class 'GoalioRememberMeDoctrineORM\Entity\RememberMe' was not found in the chain configured namespaces XXX' in X\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\MappingException.php:38 Stack trace: #0 X\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain.php(114): Doctrine\Common\Persistence\Mapping\MappingException::classNotFoundInNamespaces('GoalioRememberM...', Array) #1 X\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(113): Doctrine\Common\Persistence\Mappin in X\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\MappingException.php on line 38

i solved the problem in uncommenting the line 'remember_me_entity_class' => 'GoalioRememberMe\Entity\RememberMe' in the goaliorememberme.global.php config...but I am not sure it is the best solution....

**Comment by pdobrigkeit** [comment]
Will try to look into it. Thanks for the report.
